config/routes.rb
Rails.application.routes.draw do 
   
resources :fooditems do  
resources :orders
end 

root 'home#index'
get 'contact_us' => "home#contact_us"
get 'menu' =>"menu#index"
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fooditem.rb
class Fooditem < ApplicationRecord
has_many :orders, dependent: :destroy
validates :name, :section, :price, presence: true
validates :price, numericality: true
belongs_to :section

  
def image_url_or_default
if ima_url.present?
  ima_url
else
 "http://loremflickr.com/320/240/#{CGI.escape name}"  
end
end 

def self.find_by_section(section)
    if section
      where("section LIKE ?", "%#{section}%")
    else
      all
    end
  end

 def self.search(search)
    if search
      where("lower(name) LIKE ?", "%#{name.downcase}%")
    else
      all
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :fooditem
  validates :fooditem , :name, presence: true

end

app/models/section.rb
class Section < ApplicationRecord
  has_many :fooditems
  validates :name, presence: true, uniqueness: {case_sensitive: false}
  def self.generate_defaults
    %w(Breakfast Lunch Dinner Drinks).each do |name|
    Section.find_or_create_by(name: name)  
     end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fooditems_controller.rb
class FooditemsController < ApplicationController
  before_action :set_fooditem, only: [:show, :edit, :update, :destroy]

  # GET /fooditems
  # GET /fooditems.json
  def index
    @fooditems = Fooditem.all
  end

  # GET /fooditems/1
  # GET /fooditems/1.json
  def show
  end

  # GET /fooditems/new
  def new
    @fooditem = Fooditem.new
  end

  # GET /fooditems/1/edit
  def edit
  end

  # POST /fooditems
  # POST /fooditems.json
  def create
    @fooditem = Fooditem.new(fooditem_params)

    respond_to do |format|
      if @fooditem.save
        format.html { redirect_to @fooditem, notice: 'Fooditem was successfully created.' }
        format.json { render :show, status: :created, location: @fooditem }
      else
        format.html { render :new }
        format.json { render json: @fooditem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fooditems/1
  # PATCH/PUT /fooditems/1.json
  def update
    respond_to do |format|
      if @fooditem.update(fooditem_params)
        format.html { redirect_to @fooditem, notice: 'Fooditem was successfully updated.' }
        format.json { render :show, status: :ok, location: @fooditem }
      else
        format.html { render :edit }
        format.json { render json: @fooditem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fooditems/1
  # DELETE /fooditems/1.json
  def destroy
    @fooditem.destroy
    respond_to do |format|
      format.html { redirect_to fooditems_url, notice: 'Fooditem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fooditem
      @fooditem = Fooditem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fooditem_params
      params.require(:fooditem).permit(:description, :name, :price, :ima_url, :section)
    end

    def image_url_or_default
if ima_url.present?
  ima_url
else
 "http://loremflickr.com/320/240/#{name}"  
end

end 

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact_us
    
    end 

   
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
      def index
      @fooditems = Fooditem.all
       if params[:section] 
        @section =Section.where(name:params[:section]).first
        @fooditems = @section.fooditems
      end

      case params[:orderby]
         when  "alphabet"
        @fooditems= Fooditem.order(:name)
         when  "prlowtohigh" 
        @fooditems=Fooditem.order(:price)

        when  "prhightolow"
        @fooditems=Fooditem.order(price: :desc)
      else
        @fooditems = Fooditem.all
      end
      if params[:search]
      @fooditems= Fooditem.where("lower(title)LIKE ? OR lower(description) LIKE ?", "%#{params[:search].try(:downcase)}%", "%#{params[:search].try(:downcase)}%")
      end
      # if params[:search]
      #    @fooditems= Fooditem.where("lower(name)LIKE ? OR lower(description) LIKE ?", "%#{params[:search].try(:downcase)}%", "%#{params[:search].try(:downcase)}%")
      # end

      end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @fooditem = Fooditem.find params[:fooditem_id]
  end 

  def create
    @fooditem = Fooditem.find params[:fooditem_id]
    @order = Order.new(order_params)
    @order.fooditem = @fooditem

    if @order.save
      flash[:success] = "Order submitted. Thank you!"
      redirect_to menu_path
    else
      flash[:error] = "Error: #{@order.errors.full_messages.to_sentence}"
      render 'new'
    end
  end


   private
    def order_params
      params.require(:order).permit(:name, :phone, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fooditems_helper.rb
module FooditemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/fooditems/_form.html.erb
<%= form_for(fooditem) do |f| %>
  <% if fooditem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fooditem.errors.count, "error") %> prohibited this fooditem from being saved:</h2>

      <ul>
      <% fooditem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :ima_url %>
    <%= f.text_field :ima_url %>
  </div>

  <div class ="field">
  <%= f.label :section %>
  <%= f.text_field :section %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/fooditems/edit.html.erb
<h1>Editing Fooditem</h1>

<%= render 'form', fooditem: @fooditem %>

<%= link_to 'Show', @fooditem %> |
<%= link_to 'Back', fooditems_path %>

app/views/fooditems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fooditems</h1>

<table class ="table table-striped table-">
  <thead>

    <tr>
      <th>Description</th>
      <th>Name</th>
      <th>Price</th>
      <th>Ima url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fooditems.each do |fooditem| %>
      <tr>
        <td><%= fooditem.description %></td>
        <td><%= fooditem.name %></td>
        <td><%= food_item.price %></td>
        <td><%= fooditem.ima_url %></td>
        <td><%= link_to 'Show', fooditem %></td>
        <td><%= link_to 'Edit', edit_fooditem_path(fooditem) %></td>
        <td><%= link_to 'Destroy', fooditem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fooditem', new_fooditem_path, class:'btn btn-secondary'%>

app/views/fooditems/new.html.erb
<h1>New Fooditem</h1>

<%= render 'form', fooditem: @fooditem %>

<%= link_to 'Back', fooditems_path %>

app/views/fooditems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @fooditem.description %>
</p>

<p>
  <strong>Name:</strong>
  <%= @fooditem.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @fooditem.price %>
</p>


<p>
  <strong>Section:</strong>
  <%= @fooditem.section %>
</p>

<p>
  <strong>Ima url:</strong>
  <%= @fooditem.ima_url %>
</p>

<%= link_to 'Edit', edit_fooditem_path(@fooditem) %> |
<%= link_to 'Back', fooditems_path %>

app/views/home/contact_us.html.erb
<dive class ="container">
<h1> Contact us </h1>

<div class = "row">
<div class ="col-sm-4">
<address>
La Fenetre Soleil Coffee Shop <br>
2/F p.q.1, 44 Lý Tự trọng, Bến Nghé, Quận 1, Hồ Chí Minh, Việt Nam
</address>
</div>
<div class="col-sm-8">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.5505260299565!2d106.69487321450326!3d10.76908216227466!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f3fb4f622f9%3A0xeba7d5499f6d59d7!2sLa+Fiesta!5e0!3m2!1sen!2s!4v1476254584845" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="jumbotron">
<h1 class="display-3" >Welcome to saigon restaurant </h1>
<div class="lead">
<%= link_to "Menu", menu_path, class:'btn btn-secondary' %>
<%=link_to "Contact Us", contact_us_path, class:'btn btn-secondary' %>
</div>
</div>


  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saigonrestaurant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
  <nav class="navbar navbar-light bg-faded">
  <a class="navbar-brand" href="<%= root_path %>"> Sai gon Restaurant</a>
  <ul class="nav navbar-nav">
  <li class="nav-item">
  <%= link_to "Menu", menu_path, class:'nav-link'%>
    </li>
    <li class="nav-item">
    <%= link_to "Contact us", contact_us_path, class:'nav-link'%>
    </li>
   
  </ul>
  
</nav>
</div>
  <div class="container">
      <% if flash[:error] %>
        <div class="alert alert-danger"><%= flash[:error] %></div>
      <% end %>
      <% if flash[:success] %>
      <div class="alert alert-success"><%= flash[:success] %></div>
    <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/menu/index.html.erb
<h1>Sai Gon Restaurant </h1>
<form class="form-inline pull-xs-right">
     <%= form_tag(fooditems_path, :method => "get", id: "search-form") do %>
                        <%= text_field_tag :search, params[:search], placeholder: "Food" %>
                        <%= submit_tag "Search" %>
            <% end %>
</form>

<ul class="nav nav-pills">
<% Section.all.each do |section| %>
<li class="nav-item">
<%= link_to section.name, menu_path(section: section.name), class: "nav-link #{'active' if params[:section] == section.name}" %> 
</li>
  <% end %>
</ul>

<div class="card card-block">
<%= form_tag menu_path, method: 'get' do %>
<% if params[:section] %>
<%= hidden_field_tag :section, params[:section] %>
<% end %>
<div class="form-inline">

<%= select_tag "orderby", options_for_select([['alphabetical', 'alphabet'], ['price low to high', 'prlowtohigh'], ['price high to low', 'prhightolow']], params[:orderby]), {:prompt => 'Sort by'} %>
    <%= submit_tag "Sort", :name => nil %>
    <% end %>
  </div>
</div>

<div id="food-list">
<div class="container">
 <% @fooditems.in_groups_of(3) do |group| %>
 <div class ="row">
 <% group.compact.each do |fooditem| %>
   <div class="col-md-4">
       <div class="card">
         <%= link_to (image_tag fooditem.try(:image_url_or_default), class: 'card-img-top img-fluid'), fooditem_path(fooditem) %>
         <div class="card-block">
         <h4 class="card-title"> 
          <%= fooditem.name %> 
          <span class="label label-default"><%= fooditem.orders.size %> Orders</span>
          </h4>
           <p class="card-text"><%= fooditem.description %></p>
         </div>
         
      
              <div class="card-block">
                  <p class="card-text"><%= number_to_currency fooditem.price, locale: :vi, precision: 0 %></p>
                  <a href= <%= "/fooditems/#{fooditem.id}/orders/new"%> class="btn btn-primary">Order</a>
              </div>
       </div>
     </div>
  <% end %>
  </div>
  </div>
 </div>
<% end %>

app/views/orders/new.html.erb
<h1> <small> Order for</small> 


<%= @fooditem.name %>
</h1>
<div class ="col-sm-4">
<%= form_for [@fooditem, Order.new] do |f| %>
 <fieldset class="form-group">
 <%= f.label :name %>
 <%= f.text_field :name, class: 'form-control' %>
 </fieldset>


 <fieldset class="form-group">
 <%= f.label :phone %>
 <%= f.text_field :phone, class: 'form-control' %>
 </fieldset>

 <fieldset class="form-group">
 <%= f.label :address %>
 <%= f.text_area :address, class: 'form-control' %>
 </fieldset>

 <%= f.submit "Submit Order", class:'btn btn-primary' %>
 <% end %>
</div>